networks:
  net:
    driver: bridge

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: url-shortener-dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
    networks:
      - net
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8000/shell"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 5s
    restart: unless-stopped

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://url-shortener-dynamodb:8000
    depends_on:
      dynamodb-local:
        condition: service_healthy
    networks:
      - net
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: url-shortener-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # endpoint S3
      - "9001:9001"   # console web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - net
    restart: unless-stopped

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    container_name: url-shortener-watcher
    networks:
      - net
    environment:
      AWS_REGION: eu-west-1
      DYNAMODB_ENDPOINT: http://url-shortener-dynamodb:8000
      S3_ENDPOINT: http://url-shortener-minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      TABLE_URLS: urls
      TABLE_CLICK_EVENTS: click_events
      TABLE_DAILY_STATS: daily_stats
      FAVICONS_BUCKET: favicons
      AWS_SAM_LOCAL: "true"
      ENABLE_DDB_STREAMS: "true"
    depends_on:
      dynamodb-local:
        condition: service_healthy
      minio:
        condition: service_started
    restart: unless-stopped
